// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkvVEDd5-4atbRvEM_jegqiErH7hErhKk',
    appId: '1:862349918804:web:edef2f1ca68529007ae3c1',
    messagingSenderId: '862349918804',
    projectId: 'yummyfooddeliverypjt',
    authDomain: 'yummyfooddeliverypjt.firebaseapp.com',
    storageBucket: 'yummyfooddeliverypjt.appspot.com',
    measurementId: 'G-H8VZHQWZET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSq-570mZ6IiwfIT4RWOwoYIs2PzQlTR8',
    appId: '1:862349918804:android:14d93ab21782e42e7ae3c1',
    messagingSenderId: '862349918804',
    projectId: 'yummyfooddeliverypjt',
    storageBucket: 'yummyfooddeliverypjt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOj_t52m4Uj9y_vHwluYe1ax72OppJ3U',
    appId: '1:862349918804:ios:0f48689687ebbed67ae3c1',
    messagingSenderId: '862349918804',
    projectId: 'yummyfooddeliverypjt',
    storageBucket: 'yummyfooddeliverypjt.appspot.com',
    iosClientId: '862349918804-fshgueehgg7mj42op96100s726q06o7v.apps.googleusercontent.com',
    iosBundleId: 'com.apn.food.yummyFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmOj_t52m4Uj9y_vHwluYe1ax72OppJ3U',
    appId: '1:862349918804:ios:0f48689687ebbed67ae3c1',
    messagingSenderId: '862349918804',
    projectId: 'yummyfooddeliverypjt',
    storageBucket: 'yummyfooddeliverypjt.appspot.com',
    iosClientId: '862349918804-fshgueehgg7mj42op96100s726q06o7v.apps.googleusercontent.com',
    iosBundleId: 'com.apn.food.yummyFoodDelivery',
  );
}
